services:
  stats-server:
    build: stats
    image: stats
    container_name: stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats

  stats-db:
    image: postgres:16.1
    container_name: postgres-stats
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=stats
      - POSTGRES_USER=stats
      - POSTGRES_DB=stats

  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - main-db

  main-db:
    image: postgres:16.1
    container_name: postgres-emv
    ports:
      - "5433:5433"
